version: '3.3'
services:
  rabbit:
    image: rabbitmq:3-management
    hostname: todo_broker
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "15672:15672"
      - "5672:5672"
#  postgres:
#    image: postgres:latest
#    restart: always
#    ports:
#      - '5432:5432'
#    environment:
#      - DEBUG=false
#
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - /tmp/docker/postgresql:/var/lib/postgresql
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - /tmp/docker/mysql-datadir:/var/lib/mysql
#    launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist
